### ISSUE TITLE
fails at "starting cron" 

### ISSUE THREAD

**Issue by Dezaku** [qbxt/no-role-kick#3]
cmd just closes at "starting cron" without any message on windows 10

**Comment by jeffreyhugh** [comment]
Hi, thanks for checking my code out.

**Please try the steps described [on this SuperUser answer](https://superuser.com/a/569416) and reply with any runtime errors you uncover.** I have a theory or two, but we'll see what the errors are and go from there.

**Comment by Dezaku** [comment]
Hi, I dont know what exactly was the error, maybe my PC just needed a restart or whatever. It now works even when running the .exe normally.
Also, what is the prefix of the bot? Is there a command which I can set the time with?

**Comment by jeffreyhugh** [comment]
Nope, there are no commands. Check the `nrk.env` file to change the timeout.

I'm gonna mark this issue as resolved because the original question has been answered. If you have more questions, feel free to drop me a DM on [Discord](https://queue.bot/link/discord).
